#!/bin/bash

smb_shares=/etkon/smb-shares;

if [[ -d $smb_shares/$1 ]]; then
	dir=$smb_shares/$1;
	chmod +t $dir;
	chown -R root:root $dir;
	chmod 1775 $dir;
fi
if [[ -d $smb_shares/$1/$2 ]]; then
	dir=$smb_shares/$1/$2;
	chmod -R 755 $dir;
	chmod 1777 $dir/pool_01/todo;
fi
if [[ -d $smb_shares/$1/$3 ]]; then
	dir=$smb_shares/$1/$3;
	chmod -R 755 $dir;
	chmod 1777 $dir/chiron/pool_01/todo;
	chmod 1777 $dir/chiron/pool_01/handlers;
	chmod 1777 $dir/chiron-turnmilling/pool_01/todo;
fi
if [[ -d $smb_shares/$1/$4 ]]; then
	dir=$smb_shares/$1/$4;
	chmod -R 755 $dir;
	chmod 1775 $dir;
fi
if [[ -d $smb_shares/$1/$5 ]]; then
	dir=$smb_shares/$1/$5;
	chmod -R 755 $dir;
	chmod 1777 $dir/kern/Archiv;
	chmod 1777 $dir/kern/pool_01/pallet/todo;
fi
if [[ -d $smb_shares/$1/$6 ]]; then
	chmod 1777 $smb_shares/$1/$6;
fi
