#!/bin/bash
# for lavanya

# https://stackoverflow.com/a/246128/6353682
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";

echo "$(date)";
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_3d_printing/model/pool_01/todo" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_abutment/chiron/pool_01/todo" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_abutment/chiron/pool_01/handlers" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_abutment/chiron-turnmilling/pool_01/todo" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_disc/kern/archive" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_disc/kern/pool_01/pallet" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_disc/kern/pool_01/todo" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_standard_millings/wissner/archive" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_standard_millings/wissner/pool_01/config" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_standard_millings/wissner/pool_01/status" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_standard_millings/wissner/pool_01/todo" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/_Archiv" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/software" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/database" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/machinesoftware" | bash -x
echo "mkdir -p $DIR/examples/etch/smb-shares/nc/CARES" | bash -x
