#!/bin/bash
# for lavanya

# https://stackoverflow.com/a/246128/6353682
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";

mkdir -p $DIR/examples/etkon/smb-shares/nc/_3d_printing/model/pool_01/todo | bash -x >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_abutment/chiron/pool_01/todo >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_abutment/chiron/pool_01/handlers >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_abutment/chiron-turnmilling/pool_01/todo >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_disc/kern/archive >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_disc/kern/pool_01/pallet >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_disc/kern/pool_01/todo >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_standard_millings/wissner/archive >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_standard_millings/wissner/pool_01/config >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_standard_millings/wissner/pool_01/status >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_standard_millings/wissner/pool_01/todo >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/_Archiv >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/software >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/database >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/machinesoftware >> /tmp/log
mkdir -p $DIR/examples/etkon/smb-shares/nc/CARES >> /tmp/log
