#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";

echo "$(date)";

if [[ -d $DIR/examples ]]; then
	echo "rm -r $DIR/examples" | bash -x;
else
	echo "$DIR/examples doesn't exist" | bash -x;
fi
