FROM centos:7

ENV container docker

RUN yum -y update; yum clean all

RUN yum -y install systemd; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum -y install openssh openssh-server openssh-clients; yum clean all
RUN echo 'root:root' | chpasswd
RUN echo 'set -o vi' >> /root/.bashrc

EXPOSE 22

CMD ["/usr/sbin/init"]

# docker build --rm -t centos7-systemd - < mydockerfile
# docker run --privileged  -ti -e container=docker -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name centos --hostname centos centos7-systemd systemctl enable sshd

# postfix error & solution
# https://nixhive.com/fatal-parameter-inet_interfaces-no-local-interface-found-for-1/
