#!/usr/bin/perl

# scalar data types starts with $
# strings
$name = ethan; # quotes not required, but a convention
$t1 = "dog";
printf "My name is $name and I have a $t1.\n";
# number
$t2 = 2;
printf "My favorite number is %d.\n", $t2;

# array data types starts with @
@toys = ($t1, $t2, noname);
print "My toys are ", join(", ", @toys[2, 0]), ".\n"; # [0, 1, 2] are used for slicing what should be included on the array
print "The 3rd element on the array is ${toys[2]}.\n";

# qw operator (quote words)
@another_toys = qw[car, eggs, frisbee]; # includes comma (,) when used
print "Another set of toys are ", join(" ", @another_toys), ".\n";
# functions (print, join, etc.) don't need parenthesis but can be added to avoid ambiguity
# accessing element from array
print "I like to eat ${another_toys[1]}\n";

# hash (aka associative array) starts with %

printf "\@toys length: " . ($#toys + 1) . "\n";
